asp-netcore-web-app/Models/Character.cs
using System.ComponentModel.DataAnnotations;

namespace asp_netcore_web_app.Models
{
    public class Character
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
    }
}

asp-netcore-web-app/Models/ErrorViewModel.cs
namespace asp_netcore_web_app.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

asp-netcore-web-app/Controllers/CharacterController.cs
using asp_netcore_web_app.Data;
using asp_netcore_web_app.Models;
using Microsoft.AspNetCore.Mvc;

namespace asp_netcore_web_app.Controllers
{
    public class CharacterController : Controller
    {
        private readonly CharacterDbContext characterDb;

        public CharacterController(CharacterDbContext characterDb)
        {
            this.characterDb = characterDb;
        }

        public IActionResult Index()
        {
            IEnumerable<Character> category = characterDb.characters;
            return View(category);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Character character)
        {
            if (ModelState.IsValid)
            {
                characterDb.characters.Add(character);
                characterDb.SaveChanges();
                TempData["success"] = "Character created successfully";
                return RedirectToAction("Index");

            }
            return View(characterDb);
        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var categoryFindDb = characterDb.characters.Find(id);
            //var firstOrDefault = haracterDb.characters.FirstOrDefault(c => c.Id == id);
            //var singleOrDefault = haracterDb.characters.SingleOrDefault(c => c.Id == id);

            if (categoryFindDb == null)
            {
                return NotFound();
            }
            return View(categoryFindDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Character character)
        {
            if (ModelState.IsValid)
            {
                characterDb.characters.Update(character);
                characterDb.SaveChanges();
                TempData["success"] = "Character updated successfully";
                return RedirectToAction("Index");

            }
            return View(characterDb);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var categoryFindDb = characterDb.characters.Find(id);

            if (categoryFindDb == null)
            {
                return NotFound();
            }
            return View(categoryFindDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var category = characterDb.characters.Find(id);
            if (category == null)
            {
                return NotFound();
            }
            characterDb.characters.Remove(category);
            characterDb.SaveChanges();
            TempData["success"] = "Character deleted successfully";
            return RedirectToAction("Index");
        }
    }
}

asp-netcore-web-app/Controllers/HomeController.cs
using asp_netcore_web_app.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace asp_netcore_web_app.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

asp-netcore-web-app/Views/Character/Create.cshtml
@model Character


<form method="post">
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Create Character</h2>
			<hr />
		</div>
		<div asp-validation-summary="All"></div>
		<div class="mb-3">
			<label asp-for="FirstName"></label>
			<input asp-for="FirstName" class="form-control" />
			<span asp-validation-for="FirstName" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="LastName"></label>
			<input asp-for="LastName" class="form-control" />
			<span asp-validation-for="LastName" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Email"></label>
			<input asp-for="Email" class="form-control" />
			<span asp-validation-for="Email" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Password"></label>
			<input asp-for="Password" class="form-control" />
			<span asp-validation-for="Password" class="text-danger"></span>
		</div>
		<button type="submit" class="btn btn-primary" style="width:150px">Create</button>
		<a asp-controller="Character" asp-action="Index" class="btn btn-secondary" style="width:150px">
			Back To List
		</a>
	</div>
</form>

asp-netcore-web-app/Views/Character/Delete.cshtml
@model Character


<form method="post" asp-action="DeletePost">
	<input asp-for="Id" hidden />
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Delete Character</h2>
			<hr />
		</div>
		<div asp-validation-summary="All"></div>
		<div class="mb-3">
			<label asp-for="FirstName"></label>
			<input asp-for="FirstName" disabled class="form-control" />
			<span asp-validation-for="FirstName" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="LastName"></label>
			<input asp-for="LastName" disabled class="form-control" />
			<span asp-validation-for="LastName" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Email"></label>
			<input asp-for="Email" disabled class="form-control" />
			<span asp-validation-for="Email" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Password"></label>
			<input asp-for="Password" disabled class="form-control" />
			<span asp-validation-for="Password" class="text-danger"></span>
		</div>
		<button type="submit" class="btn btn-danger" style="width:150px">Delete</button>
		<a asp-controller="Character" asp-action="Index" class="btn btn-secondary" style="width:150px">
			Back To List
		</a>
	</div>
</form>

asp-netcore-web-app/Views/Character/Edit.cshtml
@model Character


<form method="post" asp-action="Edit">
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Edit Character</h2>
			<hr />
		</div>
		<div asp-validation-summary="All"></div>
		<div class="mb-3">
			<label asp-for="FirstName"></label>
			<input asp-for="FirstName" class="form-control" />
			<span asp-validation-for="FirstName" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="LastName"></label>
			<input asp-for="LastName" class="form-control" />
			<span asp-validation-for="LastName" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Email"></label>
			<input asp-for="Email" class="form-control" />
			<span asp-validation-for="Email" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Password"></label>
			<input asp-for="Password" class="form-control" />
			<span asp-validation-for="Password" class="text-danger"></span>
		</div>
		<button type="submit" class="btn btn-primary" style="width:150px">Update</button>
		<a asp-controller="Character" asp-action="Index" class="btn btn-secondary" style="width:150px">
			Back To List
		</a>
	</div>
</form>

asp-netcore-web-app/Views/Character/Index.cshtml
@model IEnumerable<Character>
@{
    ViewData["Title"] = "Index";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
        <h2 class="text-primary">Character List</h2>
    </div>
    <div class="col-6 text-end">
        <a asp-controller="Character" asp-action="Create" class="btn btn-primary">
            <i class="bi bi-plus-circle"></i> &nbsp; Create New Character</a>
    </div>
    </div>
    <br /> <br />
<table class="table table-bordered table-striped" style="width:100%">
    <thead>
        <tr>
            <th>
                Character Id
            </th>
            <th>
                Character First Name
            </th>
            <th>
                Character Last Name
            </th>
              <th>
                Character Email
            </th>
            <th>
                Character Password
            </th>
            <th> </th>
        </tr>
    </thead>
    <tbody>
        @foreach(var obj in Model)
        {
            <tr>
                <td>
                    @obj.Id
                </td>
                <td>
                    @obj.FirstName
                </td>
                <td>
                    @obj.LastName
                </td>
                <td>
                    @obj.Email
                </td>
                <td>
                    @obj.Password
                </td>
                  <td>
                    <div class="w-75 btn btn-group" role="group">
                        <a asp-controller="Character" asp-action="Edit" asp-route-id="@obj.Id"
                        class="btn btn-primary mx-2"><i class="bi bi-pencil-square"></i>Edit</a>
                         <a asp-controller="Character" asp-action="Delete" asp-route-id="@obj.Id"
                        class="btn btn-danger mx-2"><i class="bi bi-trash-fill"></i>Delete</a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>
</div>

asp-netcore-web-app/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

asp-netcore-web-app/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Characters</title>
    <link rel="stylesheet" href="~/css/bootswatchThemes.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BulkyBookWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarColor02">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
             <a class="nav-link" asp-controller="Character" asp-action="Index">Character</a>
        </li>
    </div>
  </div>
</nav>


    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

asp-netcore-web-app/Views/Shared/_Notification.cshtml
@if(TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
	</script>
}
@if(TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
     <script type="text/javascript">
        toastr.error('@TempData["error"]');
	</script>
}